services:
  postgres:
    container_name: GrowthLogPostgres
    image: postgres:18
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./.local/postgres-data:/var/lib/postgresql

  redis:
    container_name: GrowthLogRedis
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - ./.local/redis-data:/data
  
  minio:
    container_name: GrowthLogMinio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - ./.local/minio-data:/data
