packages:
  - workspaces/*
allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  cpu-features: true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
patchedDependencies:
  zxcvbn-ts@2.4.0: patches/zxcvbn-ts@2.4.0.patch
